### PR TITLE
add sidebar to help pages

### PR DESCRIPTION
**Pull request by gordonleacock**
Still a work in progress. See issues.

### CODE REVIEW

**Comment by respinos** [comment]
The pages do not need to replicate the contents of the help sidebar partial. We will need to tweak the application layout / create a layout for the static pages that provides the sidebar block (see https://github.com/mlibrary/umrdr/blob/master/app/views/layouts/homepage.html.erb for approach)

**Comment by gordonleacock** [comment]
I know, this was a quick hack to get it going.

**Comment by respinos** [comment]
Currently, everything uses the `blacklight.html.erb` layout --- to match that, your pages should just need to do something like

```html
<%= render partial: 'help_sidebar' %>
<div class="<%= main_content_classes %>">
        <h2>About Fishrappr</h2>
        <p>Fishrappr blah blah blah</p>
        <h4>About Fishrappr</h4>
        <p>Fishrappr blah blah blah</p>        
        <h4>About Fishrappr</h4>
        <p>Fishrappr blah blah blah</p>        
        <h4>About Fishrappr</h4>
        <p>Fishrappr blah blah blah</p>        
        <h4>About Fishrappr</h4>
        <p>Fishrappr blah blah blah</p>
</div>
```

and the the help sidebar would emit the sidebar HTML (vs. filling in the content slot):

```html
<div id="sidebar" class="<%= sidebar_classes %>">
    <h2>Help</h2>
   <!-- everything else -->
</div>
```

**Comment by gordonleacock** [comment]
Okay, I think it is time to stop with this branch and focus on the current sprint. We can come back and revise later. Roger - will you merge unless you find errors, please.

**Pull request merged**
