### PR TITLE
add home page

### PR DESCRIPTION
**Pull request by gordonleacock**
Still not connecting with Nabeela's search query from home page but otherwise good to merge.

### CODE REVIEW

**Comment by gordonleacock** [comment]
The issue _may_ be that the data range code doesn't handle a four digit year without the month and date digits too?

This is what I'm seeing in the console:

SEARCH STARTED FORM HOME PAGE -------------------------------------

Started GET "/home" for ::1 at 2016-05-27 15:39:48 -0400
Processing by StaticController#home as HTML
  Rendered static/home.html.erb within layouts/home (7.3ms)
  Rendered shared/nav/_about.html.erb (0.5ms)
  Rendered shared/nav/_help.html.erb (0.6ms)
  Rendered shared/nav/_contact.html.erb (0.6ms)
  Rendered _user_util_links.html.erb (17.8ms)
  Rendered catalog/_search_form.html.erb (2.2ms)
  Rendered static/_home_header_navbar.html.erb (44.6ms)
  Rendered static/_footer.html.erb (0.9ms)
Completed 200 OK in 516ms (Views: 515.2ms | ActiveRecord: 0.0ms)


Started POST "/catalog" for ::1 at 2016-05-27 15:40:21 -0400
Processing by CatalogController#index as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"NTPJGD/58TlO2nMBz2nGQu2dnnXqsQd6kLitbGt+vOLjZyA+LnsF0YWeIb9U2K2M+4+h0lkkLs31zWVWb0/3Fw==", "user_params"=>{"range_start"=>"1961", "range_end"=>"1970", "q"=>"president"}, "commit"=>"Search"}
  Search Load (0.3ms)  SELECT "searches".* FROM "searches" WHERE "searches"."id" IN (17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4)  ORDER BY updated_at desc
   (0.1ms)  begin transaction
  SQL (7.2ms)  INSERT INTO "searches" ("query_params", "created_at", "updated_at") VALUES (?, ?, ?)  [["query_params", "--- !ruby/hash:ActiveSupport::HashWithIndifferentAccess\nutf8: \"✓\"\nauthenticity_token: NTPJGD/58TlO2nMBz2nGQu2dnnXqsQd6kLitbGt+vOLjZyA+LnsF0YWeIb9U2K2M+4+h0lkkLs31zWVWb0/3Fw==\nuser_params: !ruby/hash:ActiveSupport::HashWithIndifferentAccess\n  range_start: '1961'\n  range_end: '1970'\n  q: president\ncontroller: catalog\naction: index\n"], ["created_at", "2016-05-27 19:40:21.172825"], ["updated_at", "2016-05-27 19:40:21.172825"]]
   (1.2ms)  commit transaction
Solr query: get select {"qt"=>"search", "facet.field"=>["date_issued_dt", "issue_no_t", "date_issued_yyyy_ti", "date_issued_yyyymmdd_ti"], "facet.query"=>[], "facet.pivot"=>[], "fq"=>[], "hl.fl"=>"full_text_txt", "rows"=>24, "qf"=>"full_text_txt", "hl"=>true, "hl.fragsize"=>0, "hl.alternateField"=>"full_text_txt", "hl.simple.pre"=>"<strong>", "hl.simple.post"=>"</strong>", "fl"=>"*", "facet"=>true, "sort"=>"date_issued_dt desc", "stats"=>"true", "stats.field"=>["date_issued_yyyy_ti", "date_issued_yyyymmdd_ti"]}
Solr fetch (62.2ms)
  Rendered .bundle/ruby/2.2.0/gems/blacklight-6.1.0/app/views/catalog/_facet_limit.html.erb (63.8ms)
  Rendered .bundle/ruby/2.2.0/gems/blacklight-6.1.0/app/views/catalog/_facet_limit.html.erb (44.3ms)
  Rendered blacklight_range_limit/_range_limit_panel.html.erb (7.6ms)
  Rendered blacklight_range_limit/_range_limit_panel.html.erb (6.8ms)
  Rendered .bundle/ruby/2.2.0/gems/blacklight-6.1.0/app/views/catalog/_facets.html.erb (148.8ms)
  Rendered .bundle/ruby/2.2.0/gems/blacklight-6.1.0/app/views/catalog/_search_sidebar.html.erb (171.4ms)
  Rendered catalog/_home_text.html.erb (0.1ms)
  Rendered .bundle/ruby/2.2.0/gems/blacklight-6.1.0/app/views/catalog/_home.html.erb (6.8ms)
  Rendered .bundle/ruby/2.2.0/gems/blacklight-6.1.0/app/views/shared/_sitelinks_search_box.html.erb (0.2ms)
  Rendered .bundle/ruby/2.2.0/gems/blacklight-6.1.0/app/views/catalog/index.html.erb within layouts/blacklight (193.7ms)
  Rendered shared/nav/_about.html.erb (0.2ms)
  Rendered shared/nav/_help.html.erb (0.2ms)
  Rendered shared/nav/_contact.html.erb (0.2ms)
  Rendered _user_util_links.html.erb (17.7ms)
  Rendered catalog/_search_form.html.erb (1.3ms)
  Rendered .bundle/ruby/2.2.0/gems/blacklight-6.1.0/app/views/shared/_header_navbar.html.erb (36.4ms)
  Rendered .bundle/ruby/2.2.0/gems/blacklight-6.1.0/app/views/shared/_ajax_modal.html.erb (0.0ms)
  Rendered .bundle/ruby/2.2.0/gems/blacklight-6.1.0/app/views/_flash_msg.html.erb (5.3ms)
  Rendered .bundle/ruby/2.2.0/gems/blacklight-6.1.0/app/views/shared/_footer.html.erb (0.0ms)
Completed 200 OK in 531ms (Views: 448.0ms | ActiveRecord: 8.9ms)


Started GET "/catalog/range_limit?authenticity_token=NTPJGD%2F58TlO2nMBz2nGQu2dnnXqsQd6kLitbGt%2BvOLjZyA%2BLnsF0YWeIb9U2K2M%2B4%2Bh0lkkLs31zWVWb0%2F3Fw%3D%3D&commit=Search&range_end=1969&range_field=date_issued_yyyy_ti&range_start=1961&user_params%5Bq%5D=president&user_params%5Brange_end%5D=1970&user_params%5Brange_start%5D=1961&utf8=%E2%9C%93" for ::1 at 2016-05-27 15:40:21 -0400
Processing by CatalogController#range_limit as HTML
  Parameters: {"authenticity_token"=>"NTPJGD/58TlO2nMBz2nGQu2dnnXqsQd6kLitbGt+vOLjZyA+LnsF0YWeIb9U2K2M+4+h0lkkLs31zWVWb0/3Fw==", "commit"=>"Search", "range_end"=>"1969", "range_field"=>"date_issued_yyyy_ti", "range_start"=>"1961", "user_params"=>{"q"=>"president", "range_end"=>"1970", "range_start"=>"1961"}, "utf8"=>"✓"}
Solr query: get select {"qt"=>"search", "facet.field"=>[], "facet.query"=>["date_issued_yyyy_ti:[1961 TO 1961]", "date_issued_yyyy_ti:[1962 TO 1962]", "date_issued_yyyy_ti:[1963 TO 1963]", "date_issued_yyyy_ti:[1964 TO 1964]", "date_issued_yyyy_ti:[1965 TO 1965]", "date_issued_yyyy_ti:[1966 TO 1966]", "date_issued_yyyy_ti:[1967 TO 1967]", "date_issued_yyyy_ti:[1968 TO 1968]", "date_issued_yyyy_ti:[1969 TO 1969]"], "facet.pivot"=>[], "fq"=>[], "hl.fl"=>"full_text_txt", "rows"=>0, "qf"=>"full_text_txt", "hl"=>true, "hl.fragsize"=>0, "hl.alternateField"=>"full_text_txt", "hl.simple.pre"=>"<strong>", "hl.simple.post"=>"</strong>", "fl"=>"*", "facet"=>true, "sort"=>"date_issued_dt desc"}
Solr fetch (8.7ms)
  Rendered blacklight_range_limit/_range_segments.html.erb (9.2ms)
  Rendered .bundle/ruby/2.2.0/gems/blacklight_range_limit-6.0.0/app/views/blacklight_range_limit/range_segments.html.erb (17.1ms)
Completed 200 OK in 81ms (Views: 67.3ms | ActiveRecord: 0.0ms)


Started GET "/catalog/range_limit?authenticity_token=NTPJGD%2F58TlO2nMBz2nGQu2dnnXqsQd6kLitbGt%2BvOLjZyA%2BLnsF0YWeIb9U2K2M%2B4%2Bh0lkkLs31zWVWb0%2F3Fw%3D%3D&commit=Search&range_end=19691210&range_field=date_issued_yyyymmdd_ti&range_start=19610627&user_params%5Bq%5D=president&user_params%5Brange_end%5D=1970&user_params%5Brange_start%5D=1961&utf8=%E2%9C%93" for ::1 at 2016-05-27 15:40:21 -0400
Processing by CatalogController#range_limit as HTML
  Parameters: {"authenticity_token"=>"NTPJGD/58TlO2nMBz2nGQu2dnnXqsQd6kLitbGt+vOLjZyA+LnsF0YWeIb9U2K2M+4+h0lkkLs31zWVWb0/3Fw==", "commit"=>"Search", "range_end"=>"19691210", "range_field"=>"date_issued_yyyymmdd_ti", "range_start"=>"19610627", "user_params"=>{"q"=>"president", "range_end"=>"1970", "range_start"=>"1961"}, "utf8"=>"✓"}
Solr query: get select {"qt"=>"search", "facet.field"=>[], "facet.query"=>["date_issued_yyyymmdd_ti:[19610627 TO 19619999]", "date_issued_yyyymmdd_ti:[19620000 TO 19629999]", "date_issued_yyyymmdd_ti:[19630000 TO 19639999]", "date_issued_yyyymmdd_ti:[19640000 TO 19649999]", "date_issued_yyyymmdd_ti:[19650000 TO 19659999]", "date_issued_yyyymmdd_ti:[19660000 TO 19669999]", "date_issued_yyyymmdd_ti:[19670000 TO 19679999]", "date_issued_yyyymmdd_ti:[19680000 TO 19689999]", "date_issued_yyyymmdd_ti:[19690000 TO 19691210]"], "facet.pivot"=>[], "fq"=>[], "hl.fl"=>"full_text_txt", "rows"=>0, "qf"=>"full_text_txt", "hl"=>true, "hl.fragsize"=>0, "hl.alternateField"=>"full_text_txt", "hl.simple.pre"=>"<strong>", "hl.simple.post"=>"</strong>", "fl"=>"*", "facet"=>true, "sort"=>"date_issued_dt desc"}
Solr fetch (5.3ms)
  Rendered blacklight_range_limit/_range_segments.html.erb (8.3ms)
  Rendered .bundle/ruby/2.2.0/gems/blacklight_range_limit-6.0.0/app/views/blacklight_range_limit/range_segments.html.erb (17.5ms)
Completed 200 OK in 68ms (Views: 59.6ms | ActiveRecord: 0.0ms)


Started GET "/catalog/opensearch.xml" for ::1 at 2016-05-27 15:40:22 -0400
Processing by CatalogController#opensearch as XML
  Rendered .bundle/ruby/2.2.0/gems/blacklight-6.1.0/app/views/catalog/opensearch.xml.builder (4.4ms)
Completed 200 OK in 11ms (Views: 10.7ms | ActiveRecord: 0.0ms)

**Comment by gordonleacock** [comment]
Okay, Nabeela and I got this working! Should be ready to merge.

**Comment by respinos** [comment]
Perhaps simple_form isn't appropriate for this form, and it should be "raw" form tags like blacklight's catalog/_search_form.html.erb?

**Comment by gordonleacock** [comment]
That had occurred to me too. That would enable cleaner search code on the
receiving end.

**Pull request merged**
